name: Core Engine CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project: [".", "games/cyberpunk-2077"]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake g++ libgtest-dev

      - name: Configure CMake
        run: cmake -S ${{ matrix.project }} -B build -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: cmake --build build --config Release

      - name: Run Tests
        if: matrix.project == '.'
        working-directory: ./build
        run: ctest --output-on-failure
